### ISSUE TITLE
License

### ISSUE THREAD

**Issue by johanvdw** [panzi/mathfun#1]
No license is specified for the files of this library.
Is it possible to declare a license? I'm reviewing a package for debian that uses one of your files, and without a formal license it can not go through.

You may find some info here:
https://choosealicense.com/

**Comment by panzi** [comment]
Interesting, who uses this? Or is it only about `portable_endian.h`? Then see: https://gist.github.com/panzi/6856583

**Comment by johanvdw** [comment]
It was indeed the portable_endian.h which is used in https://github.com/hobu/laz-perf . Thanks for clarifying (and your work!)
